merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('bands/add', views.band_create, name='band-create'),
    path('bands/<int:id>/update', views.band_update, name='band-update'),
    path('bands/<int:id>/delete', views.band_delete, name='band-delete'),
    path('about-us/', views.about),
    path('ads/', views.ad_list, name='ad-list'),
    path('ads/<int:id>/', views.ad_detail, name='ad-detail'),
    path('ads/add', views.ad_create, name='ad-create'),
    path('ads/<int:id>/update', views.ad_update, name='ad-update'),
    path('ads/<int:id>/delete', views.ad_delete, name='ad-delete'),
    path('contact-us/', views.contact, name='contact'),
    path('email-sent/', views.email_sent, name='email-sent')
]

listings/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Band(models.Model):

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(default = 'HH', choices=Genre.choices, max_length=50)
    biography = models.fields.CharField(null=True, max_length=1000)
    year_formed = models.fields.IntegerField(
        default = 2023,
        validators=[MinValueValidator(1900),MaxValueValidator(2035)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)
    
    def __str__(self):
        return f'{self.name}'

class Listing(models.Model):

    class Types(models.TextChoices):
        Records = 'R'
        Clothes = 'C'
        Posters = 'P'
        Miscellaneous = 'M'

    title = models.fields.CharField(default='', max_length=100)
    description = models.fields.CharField(default='', max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(
        default = 2023,
        validators=[MinValueValidator(1900), MaxValueValidator(2035)]
    )
    type = models.fields.CharField(default = 'R', choices=Types.choices, max_length=50)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)
    def __str__(self):
        return f'{self.title}'

listings/forms.py
from django import forms

from listings.models import Band, Listing


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)

class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        exclude = ('active', 'official_homepage') # exclue ces deux champs du formulaire généré
       # fields = '__all__'

class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = '__all__'

listings/views.py
from django.core.mail import send_mail

from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect

from listings.models import Band
from listings.models import Listing

from listings.forms import ListingForm, BandForm, ContactUsForm

def band_list(request):
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html', {'bands': bands})

def band_detail(request, id):
    band = Band.objects.get(id=id) # pour obtenir le band avec cet id
    return render(request,
            'listings/band_detail.html',
            {'band': band}) # pour passer le groupe(band)au gabarit

def band_create(request):
    if request.method == 'POST':
        # on crée une instance du formulaire qu'on rempli avec les données POST
        form = BandForm(request.POST)

        if form.is_valid():
            # creer un nouveau groupe et sauvegarde dans la bdd
            # redirection vers page de détail du groupe nouvellement crée
            band = form.save()
            return redirect('band-detail', band.id)
    else : 
        form = BandForm()

    return render(request, 
            'listings/band_create.html',
            {'form': form})

def band_update(request, id):
    band = Band.objects.get(id=id)
    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe mis a jour
            return redirect('band-detail', band.id)
    else:

        form = BandForm(instance=band) # on pré-rempli le formulaire avec les données du groupe existant.

    return render(request, 
        'listings/band_update.html',
        {'form':form})

def band_delete(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        # supprimer le groupe de la bdd
        band.delete()
        # rediriger vers la liste des groupes
        return redirect('band-list')
    # pas besoin de "else" ici. Si c'est une demande get, continuez simplement.
    return render(request,
             'listings/band_delete.html',
             {'band':band})

def about(request):
    return render(request, 'listings/about.html')

def ad_list(request):
    ads = Listing.objects.all()
    return render(request, 'listings/ad_list.html',{'ads': ads})

def ad_detail(request, id):
    ad = Listing.objects.get(id=id)
    return render(request, 
        'listings/ad_detail.html',
        {'ad': ad})

def ad_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)

        if form.is_valid():
            ad = form.save()
            return redirect('ad-detail', ad.id)
    else :
        form = ListingForm()
        
    return render(request,
        'listings/ad_create.html',
        {'form': form})

def ad_update(request, id):
    ad = Listing.objects.get(id=id)
    if request.method == 'POST':
        form = ListingForm(request.POST, instance=ad)
        if form.is_valid():
            # on sauvegarde l'annonce dans la BDD
            form.save()
            # et on redirige vers la page détaillé de l'annonce modifié
            return redirect('ad-detail', ad.id)
    else :
        
        form = ListingForm(instance = ad)

    return render(request, 
            'listings/ad_update.html',
            {'form': form})

def ad_delete(request, id):
    ad = Listing.objects.get(id=id)
    if request.method == 'POST':
        # supprimer l'annonce de la bdd
        ad.delete()
        #rediriger vers la liste des annonces 
        return redirect('ad-list')
        
    return render(request,
            'listings/ad_delete.html',
            {'ad':ad})
def contact(request):
    if request.method == 'POST':
        # créer un instance de notre formulaire et le remplir avec les données POST.
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via Merchex Contact Us Form',
                message = form.cleaned_data['message'],
                from_email = form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
            )
            return redirect('email-sent')
    else:
        # ceci doit être une requête GET, donc crée un formulaire vide.
        form = ContactUsForm()

    return render(request,
        'listings/contact.html',
        {'form':form})

def email_sent(request):
    return render(request, 'listings/email-sent.html')

listings/templates/listings/ad_create.html
{% extends 'listings/base.html' %}

{% block content%}

    <h1>Crée une nouvelle annonce</h1>

    <form action="" method="POST" novalidate>
        {% csrf_token %} 
        {{ form.as_p }}
        <input type="submit" value="Créer"/>
    </form>
{% endblock %}

listings/templates/listings/ad_delete.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1> Suppression de l'annonce </h1>

    <p>Etes-vous sûr de vouloir supprimer l'annonce <b>"{{ ad.title}}" ?</b></p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Supprimer">
    </form>

{% endblock %}

listings/templates/listings/ad_detail.html
{% extends 'listings/base.html' %}

{% block content %}
    <h2>{{ad.title}}</h2>

    <ul>
        <li>Année : {{ad.year}}</li>
        <li>vendue : {{ad.sold|yesno}}</li>
        <li>Description : {{ad.description}}</li>
    </ul>

    <a href="{% url 'ad-update' ad.id %}">[Modifier]</a>
    <a href="{% url 'ad-delete' ad.id %}">[Supprimer]</a>
    <a href="{% url 'ad-list' %}">Retour au annonces</a>

{% endblock%}

listings/templates/listings/ad_list.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1> Liste des annonces</h1>
        <ul>
            {% for ad in ads %}
                <li>
                    <a href="{% url 'ad-detail' ad.id %}">{{ad.title}}</a>
                    - <a href="{% url 'ad-update' ad.id %}">[modifier]</a>
                    - <a href="{% url 'ad-delete' ad.id %}">[Supprimer]</a>
                </li>
                
            {% endfor %}
            <p>
                <a href="{% url 'ad-create' %}"> Créer une nouvelle annonce </a>
            </p>
               
        </ul>

{% endblock %}

listings/templates/listings/ad_update.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1> Mise a jour de l'annonce </h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Modifier">
    </form>

{% endblock %}

listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1> Créer un nouveau groupe </h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Créer"/>
    </form>
{% endblock %}

listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1> Suppression du groupe </h1>

    <p> Etes vous sûr de vouloir supprimer le groupe <b>"{{ band.name }}" ?</b></p>

    <form action ="" method="post">
        {% csrf_token %}
        <input type="submit" value="Supprimer">
    </form>
{% endblock %}

listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
    <h2> {{band.name}} </h2>

    <ul>
        <li>Genre : {{ band.get_genre_display }}</li>
        <li> Année de formation : {{band.year_formed}}</li>
        <li>Actif : {{ band.active|yesno }}</li>
        {% if band.official_homepage%}
        <li>{{band.official_homepage}}</li>
        {% endif %}
    </ul>

    <p> {{ band.biography }}</p>
    <a href="{% url 'band-update' band.id %}"> Modifier ce groupe </a>
    - <a href="{% url 'band-delete' band.id %}">[Supprimer]</a>
    - <a href="{% url 'band-list'%}"> Retour à tous les groupes </a>
{% endblock %}

listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Music Bands</h1>

    <ul>
        {% for band in bands %}
        <li>
            <a href="{% url 'band-detail' band.id %}">{{ band.name}}</a>
            - <a href="{% url 'band-update' band.id %}">[modifier]</a>
            - <a href="{% url 'band-delete' band.id %}">[Supprimer]</a>
        </li>
        {% endfor %}
        
        <p>
            <a href="{% url 'band-create' %}">Créer un nouveau Band</a>
        </p>
    </ul>

{% endblock %}

listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1> Mise a jour du groupe </h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Modifier">
    </form>

{% endblock %}

listings/templates/listings/base.html
{% load static %}
<html>
    <head><title>Merchex</title></head>
    <link rel="stylesheet" href="{% static 'listings/style.css'%}" />
    <body>
        <nav>
            <a href="{% url 'band-list' %}">Groupes</a>
            <a href="{% url 'ad-list' %}">Annonces</a>
            <a href="{% url 'contact' %}">Contact</a>
        </nav>
        {% block content %}{% endblock %}
    </body>
</html>

listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1> Et si on gardait contact !</h1>
    
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Envoyer"/>
    </form>
{% endblock %}

listings/templates/listings/email-sent.html
{% extends 'listings/base.html'%}
{% block content %}

<h2> Le message a bien été envoyé </h2

{% endblock %}

listings/templates/listings/listings.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1> Liste des annonces</h1>
        <ul>
            {% for listing in listings %}
                <li>{{listing.title}}</li>
            {% endfor %}
        </ul>

{% endblock %}